### ISSUE TITLE
problem with addding js to language configs

### ISSUE THREAD

**Issue by mehrnazayazi** [QingdaoU/JudgeServer#16]
I have added this config to language configs:
```
js_lang_config = {
   "run": {
       "exe_name": "solution.js",
       "command": "/usr/bin/nodejs {exe_path}",
       "seccomp_rule": "general",
   }
}
```
and this line to Dockerfile
`RUN apt-get install -y nodejs`

any code that is run with js language config returns runtime error.
when I run the code directly from docker I get the correct result I'm expecting

**Comment by virusdefender** [comment]
firstly you can try to use `seccomp_rule=None`
