### ISSUE TITLE
problem with using docker-compose deploying JudgeServer

### ISSUE THREAD

**Issue by zijinggao** [QingdaoU/JudgeServer#19]
在安装好了最新版本的docker和docker-compose后，想要直接用judgeserver中的.yml文件直接部署，在下载好.yml文件后使用docker-compose -f docker-compose.example.yml up命令后，停留在如下所示的情况，进程没有结束，但是无论等多久也没有变化了。请问这是什么原因，为什么部署不成功？谢谢！
8f7e12270ec5_judgeserver-master_judge_server_1 is up-to-date
Attaching to 8f7e12270ec5_judgeserver-master_judge_server_1

**Comment by virusdefender** [comment]
只  `up` 没有 `-d` 就会这样，不过使用应该是正常的。加 `-d` 是 deamon 模式。
