### ISSUE TITLE
The problem of using third party Library

### ISSUE THREAD

**Issue by zijinggao** [QingdaoU/JudgeServer#21]
请教一下，在单调用judgeserver评测机时，想要加第三方库，在dockerfile中的run 后面添加了想要加入的包后，要如何重构镜像，放在docker-compose.yml文件中，让其他的配置都不变，能够正常运行呢？谢谢您！
![qq 20181102150429](https://user-images.githubusercontent.com/25921426/47898656-b6aa6c80-deb1-11e8-9d24-e248d0574eab.png)

**Comment by virusdefender** [comment]
因为 numpy 可能使用了一些黑科技，不是太确定。如果确实有需要，可以尝试在 backend 那边对 Python 设置不使用 seccomp（会降低安全性）
