### ISSUE TITLE
服务器环境下不能导入题目

### ISSUE THREAD

**Issue by developers-youcong** [QingdaoU/JudgeServer#25]
Linux环境Ubuntu16.04不能导入题目，导入题目出现Server Error。我们环境是用阿里云服务器的。但是本地Linux也是Ubuntu16.04，导入题目却没有出现Server Error 能够正常导入题目。请问下，这是什么原因?谢谢

**Comment by mikucat0309** [comment]
正在整理 issue 與 PR，有需要再重新打開或開新的 issue 吧。
