### ISSUE TITLE
[API] get JudgeClientError, "ping() argument after ** must be a mapping, not NoneType"

### ISSUE THREAD

**Issue by dyhe83** [QingdaoU/JudgeServer#27]
你好，

我參考 [judgeserver api](https://docs.onlinejudge.me/#/judgeserver/api?id=get-system-info) 寫一個python程式想要檢查`system info`。
```python
import hashlib
import requests

token = hashlib.sha256('CHANGE_THIS'.encode('utf-8')).hexdigest()
headers = {'X-Judge-Server-Token': str(token), }
response = requests.post('http://172.18.0.3:8080/ping', headers=headers)
print(response.content)
```

卻得到 `JudgeClientError` 錯誤：
```json
{"data": "TypeError :ping() argument after ** must be a mapping, not NoneType", "err": "JudgeClientError"}
```

請問怎麼解決??

**Comment by virusdefender** [comment]
try tp add an empty body `response = requests.post('http://172.18.0.3:8080/ping', headers=headers, json={})`

https://github.com/QingdaoU/JudgeServer/blob/master/client/Python/client.py

**Comment by dyhe83** [comment]
solved, thanks for your quick response!
