### ISSUE TITLE
entrypoint.sh多次调用导致多个gunicorn进程同时存在占用内存

### ISSUE THREAD

**Issue by nkcs2016** [QingdaoU/JudgeServer#32]
外部的一个服务，能够通过entrypoint.sh启动这个docker里的服务，那个服务反复重启导致docker的内存爆炸。建议每次运行entrypoint.sh的时候先杀掉之前的gunicorn进程

**Comment by virusdefender** [comment]
你应该是 docker restart 才对，而不是启动 entrypoint
