### ISSUE TITLE
请问有人遇到测试用例找不到之后进程睡眠占用内存的问题吗？

### ISSUE THREAD

**Issue by KahungLee** [QingdaoU/JudgeServer#37]
日志：
2020-06-14 16:29:02,547 ERROR 
Traceback (most recent call last):
  File "/code/judge_client.py", line 51, in _load_test_case_info
    with open(os.path.join(self._test_case_dir, "info")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/test_case/1/info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/server.py", line 189, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 144, in judge
    output=output)
  File "/code/judge_client.py", line 36, in __init__
    self._test_case_info = self._load_test_case_info()
  File "/code/judge_client.py", line 54, in _load_test_case_info
    raise JudgeClientError("Test case not found")

查看实时进程：

root@4104fd566a2c:/# top
top - 23:20:36 up  8:07,  0 users,  load average: 0.19, 0.19, 0.22
Tasks:  11 total,   1 running,  10 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.3 us,  1.3 sy,  0.0 ni, 97.0 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   498728 total,    17624 free,   198344 used,   282760 buff/cache
KiB Swap:  2097148 total,  1934332 free,   162816 used.   187844 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
   16 root      20   0  709756  24468   2844 S  0.3  4.9   0:08.57 gunicorn
    1 root      20   0    4492    564    548 S  0.0  0.1   0:00.05 sh
    5 root      20   0   60584  14904   2448 S  0.0  3.0   0:01.46 gunicorn
   15 root      20   0  683012  23916   2476 S  0.0  4.8   0:08.10 gunicorn
   34 root      20   0  166876  22216    964 S  0.0  4.5   0:00.00 gunicorn
   56 root      20   0   18256   1576   1076 S  0.0  0.3   0:00.09 bash
  164 root      20   0  240604  22228    972 S  0.0  4.5   0:00.00 gunicorn
  171 root      20   0  461816  22380    960 S  0.0  4.5   0:00.00 gunicorn
  178 root      20   0  461820  22396    968 S  0.0  4.5   0:00.00 gunicorn
 4591 root      20   0   36652   1668   1244 R  0.0  0.3   0:00.06 top
 4723 root      20   0  709756  22752   1068 S  0.0  4.6   0:00.00 gunicorn

所有进程：
root@4104fd566a2c:/# ps aux | more
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1   4492   564 ?        Ss   21:56   0:00 /bin/sh -c /code/entrypoint.sh
root         5  0.0  2.8  60584 14096 ?        S    21:56   0:01 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root        15  0.1  4.7 683012 23444 ?        Sl   21:57   0:09 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root        16  0.1  4.8 709756 23992 ?        Sl   21:57   0:10 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root        34  0.0  4.3 166876 21740 ?        S    21:57   0:00 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root        56  0.0  0.3  18256  1632 pts/0    Ss   21:57   0:00 /bin/bash
root       164  0.0  4.3 240604 21752 ?        S    21:59   0:00 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root       171  0.0  4.3 461816 21908 ?        S    21:59   0:00 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root       178  0.0  4.3 461820 21928 ?        S    21:59   0:00 /usr/bin/python3 /usr/local/bin
/gunicorn --workers 2 --threads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:80
80 server:app
root      4723  0.0  4.4 709756 22276 ?        S    23:20   0:00 /usr/bin/python3 /usr/local/bin/gunicorn --workers 2 --thr
eads 2 --error-logfile /log/gunicorn.log --time 600 --bind 0.0.0.0:8080 server:app
root      5434  0.0  0.2  34412  1432 pts/0    R+   23:33   0:00 ps aux
root      5435  0.0  0.1   6588   696 pts/0    S+   23:33   0:00 more

**Comment by mikucat0309** [comment]
正在整理 issue 與 PR，有需要再重新打開或開新的 issue 吧。
