### ISSUE TITLE
关于评测队列

### ISSUE THREAD

**Issue by chenhongqiao** [QingdaoU/JudgeServer#39]
请问当多个用户同时提交代码时评测机会怎么处理？同时评测多个还是一次一个，前一个结束之后再测下一个？

**Comment by virusdefender** [comment]
JudgeServer 不管队列，由上层调度

**Comment by chenhongqiao** [comment]
上层指的是？请问上层的具体调度策略是什么？

**Comment by virusdefender** [comment]
上层的代码是你自己实现的，或者参考 https://github.com/QingdaoU/OnlineJudge
