### ISSUE TITLE
能否支持下JavaScript语言?

### ISSUE THREAD

**Issue by Sky-J** [QingdaoU/JudgeServer#43]
我们在使用这个平台在公司内举办比赛 前端们也很希望参加进来 但是发现语言不支持 希望大佬们考虑一下~

**Comment by virusdefender** [comment]
加一个 node 进去应该不难

**Comment by Robin3910** [comment]
> 加一个 node 进去应该不难

大佬可以介绍一下添加JS语言的方法吗，或者加wx私聊一下，我这边有人可以帮忙开发扩展JS这块

**Comment by chunyangjiamr** [comment]
node加了吗，或者是javascript的类型，我这边准备加一下，但是还是有些不懂的，能否高人指点一二？

**Comment by virusdefender** [comment]
支持了，拉一下镜像，然后还得看下 https://opensource.qduoj.com/#/onlinejudge/guide/update_compile_options 运行 `SysOptions.reset_languages()`
