### ISSUE TITLE
Getting the following error. How to resolve this ?

### ISSUE THREAD

**Issue by erainterfacesindia** [QingdaoU/JudgeServer#49]
Compile Error
/judger/run/1d3f9a7de8a3467d9f7544015811b33c/main.c:10:5: error: redefinition of 'main'
 int main() {
     ^~~~
/judger/run/1d3f9a7de8a3467d9f7544015811b33c/main.c:4:5: note: previous definition of 'main' was here
 int main(){
     ^~~~

![Screen Shot 2021-05-25 at 2 11 41 PM](https://user-images.githubusercontent.com/80757255/119467642-56c38c00-bd63-11eb-803c-d0f710dc2c16.png)

**Comment by virusdefender** [comment]
this problem is using `code template` function,  your code will be inserted to the template, so there may be multi main functions, you should only submit the missing code.

![image](https://user-images.githubusercontent.com/4939404/119469740-3b17b000-bd7a-11eb-9ef5-45d01a2c7e2b.png)

**Comment by erainterfacesindia** [comment]
Thanks for the quick reply, It's working fine now, But getting the following error, even though the code is fine. 
Can u let me know your thoughts on this 
![Screen Shot 2021-05-25 at 2 35 36 PM](https://user-images.githubusercontent.com/80757255/119471129-a192d300-bd66-11eb-9418-5ca7d607d789.png)
