### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by nikhilpalde** [QingdaoU/JudgeServer#50]
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c: In function 'main':
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c:7:5: error: 'cout' undeclared (first use in this function)
     cout << "Before swapping." << endl;
     ^~~~
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c:7:5: note: each undeclared identifier is reported only once for each function it appears in
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c:7:35: error: 'endl' undeclared (first use in this function)
     cout << "Before swapping." << endl;
                                   ^~~~
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c: At top level:
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c:19:5: error: redefinition of 'main'
 int main() {
     ^~~~
/judger/run/6a9d0d474dca4801b1806774b861a619/main.c:3:5: note: previous definition of 'main' was here
 int main()
     ^~~~
![Issue 1](https://user-images.githubusercontent.com/84841592/120215971-07de9080-c254-11eb-8542-246d00ab3012.PNG)

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/JudgeServer/issues/49
