### ISSUE TITLE
Build Docker镜像失败

### ISSUE THREAD

**Issue by akira-cn** [QingdaoU/JudgeServer#53]
DockerFile 里面这一段 ` echo $phpJitOption > /etc/php/8.0/cli/conf.d/10-opcache-jit.ini`，需要改成 php/8.1，因为现在8.1是正式版本，默认前面会安装PHP8.1，所以目录不对了，这个地方可能需要调整一下，不然之后8.2如果出来了又要改。

**Comment by mikucat0309** [comment]
JudgeSerer 沒有實際用到 PHP，v1.6.0 已經把 PHP 拔掉了。

---

正在整理 issue 與 PR，有需要再重新打開或開新的 issue 吧
