### ISSUE TITLE
使用项目里面的Dockerfile构建失败

### ISSUE THREAD

**Issue by 1179514691** [QingdaoU/JudgeServer#55]
我想问一下,我使用命令构建项目里面的Dockerfile文件报错应该怎么处理呢?
报错内容如下:
![image](https://user-images.githubusercontent.com/56039207/180014766-feffd4f2-f307-4a26-aaf0-cee2002e2cfd.png)

**Comment by mikucat0309** [comment]
應該是被牆了，不過 1.6 之後沒用到 PPA。

---

正在整理 issue 與 PR，有需要再重新打開或開新的 issue 吧
