### ISSUE TITLE
service.py 每隔6秒执行一次，请问这个是怎么实现的，能不能将时间改长一点。谢谢

### ISSUE THREAD

**Issue by yyy1004** [QingdaoU/JudgeServer#57]

**Comment by mikucat0309** [comment]
由 Dockerfile 的 `HEALTHCHECK` 定義的，向 web backend 發送 heartbeat 也依賴這個腳本，所以目前不能改長。

---

正在整理 issue 與 PR，有需要再重新打開或開新的 issue 吧
