### ISSUE TITLE
Judge Server Failed

### ISSUE THREAD

**Issue by andyjjrt** [QingdaoU/JudgeServer#58]
Thanks for the maintainance, I'm trying to use the latest judge server, the building process is fine, but its health check fails, which makes backend server down. Seems like the new setup have some error.

**Comment by mikucat0309** [comment]
Can your provide the detail error about health checking?

below is the health check command used in judge server Docker image
```sh
docker compose exec oj-judge /app/.venv/bin/python3 /app/service.py
```

**Comment by andyjjrt** [comment]
After reinstall docker, the problem seems to be solved. Thanks for replying
