### ISSUE TITLE
为什么不把JudgeServer的input,output弄成json传值

### ISSUE THREAD

**Issue by Smith-Cruise** [QingdaoU/JudgeServer#7]
我看了下文档，现在judger判卷是根据本地的`.in`, `.out` 文件，为什么不做成json传递的。像[HackerRank](https://www.hackerrank.com/api/docs)那样的api，这样我们更加容易自己开发，也可以参考下另一个开源项目[Judge0](https://api.judge0.com/)

**Comment by virusdefender** [comment]
有的测试用例文件很大的，每次都传过去还是有些浪费。如果需要同步，请用 rsync。
